### ISSUE TITLE
Step definitions/glue files not found on macOS

### ISSUE THREAD

**Issue by LewisCraik** [cucumber/vscode#100]
### 👓 What did you see?

I have one feature file `duckduckgo.feature` and one step definition file `duckduckgo.js` both located in the `cypress/e2e` folder. My plugin settings are as below:

```
{
  "cucumber.features": [
    "cypress/e2e/*.feature"
  ],
  "cucumber.glue": [
    "cypress/e2e/*.js"
  ]
}
```

However the .feature file is recognised, but the .js file is not. This is the output:
```
[Info  - 4:27:56 PM] Registering request handler for workspace/didChangeConfiguration failed.
[Info  - 4:27:56 PM] Client does not support client/registerCapability. This is OK.
[Info  - 4:27:56 PM] Cucumber Language Server 0.12.11 initialized
[Info  - 4:27:56 PM] Scheduling reindexing in 3000 ms
[Info  - 4:27:56 PM] Reindexing...
[Info  - 4:27:56 PM] * Found 1 feature file(s) in ["cypress/e2e/*.feature"]
[Info  - 4:27:56 PM] * Found 3 steps in those feature files
[Info  - 4:27:56 PM] * Found 0 glue file(s) in ["cypress/e2e/*.js"]
[Info  - 4:27:56 PM] * Found 0 parameter types in those glue files
[Info  - 4:27:56 PM] * Found 0 step definitions in those glue files
[Info  - 4:27:56 PM] * Built 3 suggestions for auto complete
[Info  - 4:27:56 PM] Unable to generate step definition. Please create one first manually.
[Info  - 4:27:56 PM] Unable to generate step definition. Please create one first manually.
[Info  - 4:27:57 PM] Unable to generate step definition. Please create one first manually.
[Info  - 4:27:59 PM] Reindexing...
[Info  - 4:27:59 PM] * Found 1 feature file(s) in ["cypress/e2e/*.feature"]
[Info  - 4:27:59 PM] * Found 3 steps in those feature files
[Info  - 4:27:59 PM] * Found 0 glue file(s) in ["cypress/e2e/*.js"]
[Info  - 4:27:59 PM] * Found 0 parameter types in those glue files
[Info  - 4:27:59 PM] * Found 0 step definitions in those glue files
[Info  - 4:27:59 PM] * Built 3 suggestions for auto complete
[Info  - 4:27:59 PM] Unable to generate step definition. Please create one first manually.
[Info  - 4:27:59 PM] Unable to generate step definition. Please create one first manually.
```

### ✅ What did you expect to see?

I would have expected the .js file to be seen and the step definitions to be recognised.

### 📦 Which tool/library version are you using?

I am using Cypress v10.6 with [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) v12.1, VSCode v1.70.2 and plugin version v1.2.8. I have noticed this on earlier versions of Cypress and the Cypress Cucumber Preprocessor too.

### 🔬 How could we reproduce it?

1. Set up a Cypress project.
2. Ensure Cucumber plug in settings are pointing to the location of the files to be created.
3. Add a feature file.
4. Add a JavaScript step definitions file to define the steps in the feature file.
5. Plugin should recognise glue file, but doesn't.

### 📚 Any additional context?

I am on an M1 Mac

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by aslakhellesoy** [comment]
JavaScript is not supported. You can contribute support if you want. See https://github.com/cucumber/language-service/issues/42
