### ISSUE TITLE
Glue config not working

### ISSUE THREAD

**Issue by danielferromeral** [cucumber/vscode#129]
### 👓 What did you see?
.feature:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/47207636/204841219-8838a50d-04d0-468f-acb0-b26702511693.png">

setdefs.js
<img width="401" alt="image" src="https://user-images.githubusercontent.com/47207636/204836919-2fe94c09-3fd4-4c34-8f73-a212da03c24c.png">

Both user and workspace settings:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/47207636/204837561-7c0f3753-d3b7-4791-804b-677af62d48d8.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/47207636/204840877-7f4198b2-2658-4f04-95cc-c0c5b387d15b.png">

File structure:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/47207636/204836692-7140677a-8f31-469b-972b-3a64ee158763.png">

The autocomplete is not working. I saw that, by default, the .js files are not inside the glue property, so I change it, but it still doesn't work. When I run cucumber the test pass successfully.

### ✅ What did you expect to see?

The autocomplete working.

### 📦 Which tool/library version are you using?

package.json
```json
{
  "name": "cucumber-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "cucumber-js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@cucumber/cucumber": "^8.9.0"
  },
  "dependencies": {
    "chai": "^4.3.7"
  }
}
```

Extension is 1.6.0
VS is 1.73.1

### 🔬 How could we reproduce it?

1. Create a feature with a step
2. Create a step to that feature with .js
3. Add to the setting:
```json
   "cucumber.glue": [
         "features/**/*.js"
   ]
```

**Comment by aslakhellesoy** [comment]
Support for JavaScript was released in [1.7.0](https://github.com/cucumber/vscode/blob/main/CHANGELOG.md#170---2022-12-08)
