### ISSUE TITLE
Add support for cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by zilia-gmethot** [cucumber/vscode#134]
When using https://github.com/badeball/cypress-cucumber-preprocessor, some features are not working properly:
- Step definitions starting by the "And" are always considered undefined
- Step definitions defined using the library's `defineStep` function are always considered undefined

It would be great if support for the library was added. Thank you!

**Comment by riker09** [comment]
I discovered this extension today which is adding a long missing feature to VSCode: Jumping straight to a step definition from a feature file. Awesome! 👍🏻 🚀 

It seems that the step definitions starting with `And` are working, though? Maybe something was changed while this ticket was created. Anyway, just wanted to leave this here as "it works on my machine".

**Comment by zilia-gmethot** [comment]
The `And` and `But` keywords have actually been deprecated in newer versions. It also looks like `defineStep` is being deprecated by CucumberJS.

Links of interest:
- https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#function-members-and-and-but-are-missing
- https://github.com/cucumber/cucumber-js/issues/2043
