### ISSUE TITLE
@And annotated steps are not see by the autocomplete

### ISSUE THREAD

**Issue by peterdstone** [cucumber/vscode#147]
### 👓 
@And annotated steps are not see by the autocomplete

### ✅ 
auto complete should highlite @And defined steps 

### 📦 
io.cucumber:cucumber-java:7.7.0,
Java 17,
vscode 1.76.1
plugin 1.7.0

### 🔬 create a java feature file with @And annotated steps

1. add @Annotated method to java class
2. configure class to be picked up by glue settings
3. start writing .feature file
4. try to use step

![image](https://user-images.githubusercontent.com/20043507/224722868-4c13e206-36a7-4941-9b9e-0facfdbe0961.png)

![image](https://user-images.githubusercontent.com/20043507/224723644-0e6a4ab7-99d0-438c-9229-d2cb11b89aa9.png)

**Comment by jimmyko** [comment]
@peterdstone I think `@And` is deprecated
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#function-members-and-and-but-are-missing

**Comment by jeeeem** [comment]
I wanted to this ask too, is this now the current behavior of this as a general standard when working with cucumber, that I have to change all the `@And` annotated methods to `@Given` since I cannot use to `Go to Definition` if I do not did that?

**Comment by jenisys** [comment]
Mmh, you normally only need `@Given`, `@When` and `@Then` (3 step types).
`And` and `But` in Gherkin files are only used to state `Use the same step-type than before myself`. This means, you inherit the `step-type` from one of the steps before (that is not `And` or `But`).

BUT: In the step-implementation, you need to state which `step-type` is used.
This allows you also to change the ordering of steps.

**Comment by jeeeem** [comment]
> Mmh, you normally only need `@Given`, `@When` and `@Then` (3 step types). `And` and `But` in Gherkin files are only used to state `Use the same step-type than before myself`. This means, you inherit the `step-type` from one of the steps before (that is not `And` or `But`).
> 
> BUT: In the step-implementation, you need to state which `step-type` is used. This allows you also to change the ordering of steps.

Okay, so I will take it as yes on my question.
