### ISSUE TITLE
Todays broken Gherkin to implementation steps navigation 

### ISSUE THREAD

**Issue by TsypliakAlexandr** [cucumber/vscode#162]
Visual Studio Code
Version: 1.78.0
OS: Windows 10

I was using CucumberJS together with Node 16.17.1 using Visual Studio code and the Cucumber plugin for convenient navigation between features and implementation steps. I did last git commit near 24 hours ago and all was working fine.

But when I opened the project today I found at once after start some errors in output console: 

[Error - 7:26:30 AM] Server initialization failed.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
[Error - 7:26:30 AM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 

My collogues with other valid projects using CucumberJS started to face the same issue yesterday.

Concerning that it started for multiple people exactly yesterday without changes in environments or projects themselves.

Is there a chance that it is a problem on side of plugin itself?

**Comment by arjunhamdalah** [comment]
Duplicate of #155

**Comment by TsypliakAlexandr** [comment]
So yes I was wrong.

I didn't notice AutoUpdate of Visual Studio code to 1.78.0 

Guess for this version this functionality never worked as expected.

As mentioned [aleksdobrev](https://github.com/aleksdobrev) in https://github.com/cucumber/vscode/issues/155 the easiest way to resolve the issue was just to downgrade Visual Studio code back to 1.77.3
