### ISSUE TITLE
Format Document with cucumber removes the commented Gherkin steps  

### ISSUE THREAD

**Issue by kannanmf** [cucumber/vscode#163]
### 👓 What did you see?

1. Comment some gherkin steps (Given/When/Then/And/But) inside a feature file.
2. Right-click and click on Format Document
3. Commented Gherkin steps removed automatically

### ✅ What did you expect to see?

It should not remove any commented gherkin steps instead it should only format the feature file

### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by tim-yao** [comment]
Agreed. Sometimes, we need comments on the feature for maintenance reasons.
