### ISSUE TITLE
[Error - Server initialization failed.

### ISSUE THREAD

**Issue by hzi1193** [cucumber/vscode#171]
Good afternoon, the following error occurs when loading the cucumber plugin

[Error - 11:11:32 AM] Server initialization failed.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
[Error - 11:11:32 AM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603

**Comment by yann-combarnous** [comment]
Same error here

**Comment by Rajpratik71** [comment]
👍 

Same here.

From some time (approx some month) it is just crashing.

Checked there is no updated happned , same release was working earlier.

Failing with same error

`
[Error - 4:41:01 PM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
`


`
Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
`

**Comment by msundresh** [comment]
Same here

**Comment by xuanthanhtsd** [comment]
Same here

**Comment by RAM10193** [comment]
same issue am facing

**Comment by iq0104grace** [comment]
I'm facing the same issue

**Comment by wayneiag** [comment]
I am also facing the same issue , has there been any progress on this

**Comment by iq0104grace** [comment]
To provide more information, my machine is macOS 13.4.1 (c) (22F770820d), Visual Studio Code is on Version: 1.80.2

**Comment by xeger** [comment]
Thank you for the bug report. This is fixed in [v1.8.0](https://github.com/cucumber/vscode/releases/tag/release%2Fv1.8.0) which should be published to the Visual Studio Code Marketplace soon, or you can install from the `.vsix` file in the linked release.
