### ISSUE TITLE
Explicit unicode strings in Python step definition patterns

### ISSUE THREAD

**Issue by nopa12** [cucumber/vscode#173]
when i use unicode strings:
```
@given(u'I fill the settings form with real valid settings')
```
feature:
```
     Given I fill the settings form with real valid settings
```

behave works but cucumber extension doesn't see the `u` string `given` and report it as missing.
```
Undefined step: I fill the settings form with real valid settingsCucumber[cucumber.undefined-step](https://cucumber.io/docs/cucumber/step-definitions/)
```

when i remove the `u` it works. 
i don't know if it's a bug or on purpose.

**Comment by jenisys** [comment]
@nopa12 
* `behave` currently shows missing steps with `u“…“` due to compatibility with Python2.7 (and older Python3) version(s).
* If you are using Python3, you have no need to use the Unicode-String prefix
* Unicode-String prefix support will become deprecated in Python 3.12 (I think)
