### ISSUE TITLE
Extension not released to marketplace due to publishing issue

### ISSUE THREAD

**Issue by KishorkumarKR-iamneo** [cucumber/vscode#178]
### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by timhemming-fico** [comment]
Hi. Is there any news on the Cucumber VSCode extension being published to the marketplace? My team were waiting on this, we've had to install from the download for now.

**Comment by patrickschilder** [comment]
Would be great to have this update in the store, as i don't want to have my team members installing this manually.

**Comment by patrickschilder** [comment]
Such a waste to have a working version, but not having it available in the marketplace

**Comment by patrickschilder** [comment]
@xeger any idea when it will be available in the marketplace?

**Comment by xeger** [comment]
Our apologies for the delay. We have just heard back from Microsoft and resolved a publishing issue; @mattwynne and I will work together this month to produce a new release in the Marketplace.

**Comment by mpkorstanje** [comment]
This should be fixed now. 1.8.1 was just released.
