### ISSUE TITLE
Unable to go to step definition from feature file with Java serenity project

### ISSUE THREAD

**Issue by srninni** [cucumber/vscode#181]
### 👓 What did you see?

Not able to go to step definition from feature file. Getting a message, "Steps not found". Steps are there and even the tests are working, running successfully.

### ✅ What did you expect to see?

On right clicking on the gherkin statement and choode "Go to Step", i should land on the step

### 📦 Which tool/library version are you using?

serenity cucumber in Java
### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment]
Hi @srninni, thanks for raising. Could you provide more information on the software versions used (serenity, VSCode, VSCode Cucumber extension) and the relative path to where your step definitions and feature files are stored?

**Comment by srninni** [comment]
Hi @kieran-ryan, thanks for the response, 
I tried both serenity version 2.0.39 and 4.0.0-beta-2
For VS Code Cucumber extension, I have v1.7.0
VS Code version 1.83.1

**Comment by kieran-ryan** [comment]
@srninni, can you provide:

- an example feature file - and its relative path to the root of your workspace
- an example step definition - and its relative path to the root of your workspace
- any configured [extension settings](https://github.com/cucumber/vscode#extension-settings) - suggest to double-check the paths to your glue and feature files match the default glob paths

**Comment by kieran-ryan** [comment]
@srninni, have experimented with Serenity and suspect the issue relates to the [Cucumber Language Service not supporting the `@Step` and `@But` decorators](https://github.com/cucumber/language-service/blob/4ea562ad437e7fe27cfb5d39ecf7928e51bd138c/src/language/javaLanguage.ts#L93). Otherwise, expression parsing errors can be observed in [VSCode's Output window for the 'Cucumber Language Server'](https://raw.githubusercontent.com/cucumber/vscode/main/images/vscode-output.png).

@mpkorstanje, for the Cucumber JVM, would you be able to advise are the supported decorators `@Step`, `@And`, `@But`, `@Given`, `@When`, `@Then`? And should we extend parsing support to all those decorators or keep to `@Given`, `@When`, and `@Then`? I will extend support if considered advisable.

**Comment by mpkorstanje** [comment]
Cucumber JVM generates the annotations from [gherkin-languages.json](https://github.com/cucumber/gherkin/blob/main/gherkin-languages.json#L791) with [some small modifications](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-java/src/codegen/java/GenerateI18n.java) to make it valid Java.

So not only is that Given, When, Then, and also And and But. But also every translation of those keywords.

For Serenity, from reading the docs, the @Step annotation is not for step definitions, but rather for logging. 

https://serenity-bdd.info/docs/serenity/#first-steps

So to peel this onion, I think adding support for all the English keywords would be a first step. 

To add support for all the other translations, there are a few options I suppose you could investigate. If the language service supports meta annotations you could look for the presence of the [`@StepDefinitionAnnotation`](https://github.com/cucumber/cucumber-jvm/blob/f4728849b92f963adbc2821047565f5ed1d7067e/cucumber-java/src/codegen/resources/templates/annotation.java.ftl#L34) meta annotation. If not then it might be possible to generate all the keywords from the `gherkin-languages.json`.
