### ISSUE TITLE
Steps with <> parameters are not detected

### ISSUE THREAD

**Issue by massDefect7** [cucumber/vscode#182]
### 👓 What did you see?

All steps in the feature file are detected and are displayed as suggestions. 
Except the steps that defined for Scenario Outlines. 
These steps use parameters and are implemented parsers.parse (for lack of a better option).

### ✅ What did you expect to see?

I expected to have all steps detected and displayed as suggestions.

### 📦 Which tool/library version are you using?

Python - 3.11.5
pytest-bdd - 7.0.0
VS Code - 1.84.2
Cucumber (Gherkin) extension - v2.15.2

### 🔬 How could we reproduce it?

1. Install 'VS Code' version '1.84.2'
2. Install 'Cucumber (Gherkin) extension' version 2.15.2
3. Create feature file with scenario outline
4. Implement steps in step definition file  
5. Check the step detection and auto complete
6. Steps with parameters are not detected

Scenario Outline:
![screen_ 2023-11-10 12 46 33](https://github.com/cucumber/vscode/assets/59473688/03fc2826-6b7b-4d7c-954e-45e66621eb99)
Step definitions:
![screen_ 2023-11-10 12 59 28](https://github.com/cucumber/vscode/assets/59473688/77fb385b-d13a-4b53-be11-227ffc90b654)

### 📚 Any additional context?
 none

**Comment by kieran-ryan** [comment]
Hi @massDefect7, as the extension number mentioned is 2.15.2, you appear to be using the [Cucumber (Gherkin) Full Support](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete) extension. This repository relates to the [official Cucumber extension](https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official) - which is at version 1.7.0 in the Visual Studio Code marketplace.

Note: The official extension does not support diagnostics for whether a step is undefined when using Scenario Outlines - see cucumber/language-service#149.
