### ISSUE TITLE
Language pt-br

### ISSUE THREAD

**Issue by tulavalle** [cucumber/vscode#187]
### 🤔 What's the problem you're trying to solve?

Use the documenting tool in the pt-br language.

### ✨ What's your proposed solution?

Configuration in the settings of the .vscode folder that allows choosing the default language for writing feature files

### ⛏ Have you considered any alternatives or workarounds?

Extension from other suppliers, but the quality and resources offered are much lower than what is provided by this tool.

### 📚 Any additional context?

--//--

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by kieran-ryan** [comment]
Thanks for raising @tulavalle, capturing this as a duplicate #141 - to provide support and configuration for [parser-supported languages](https://cucumber.io/docs/gherkin/languages/). Would be great if you can leave an upvote (👍) on that issue, thanks!
