### ISSUE TITLE
Release v1.8.0 is not available on any marketplace  due to failed  release Action

### ISSUE THREAD

**Issue by seanlilmateus** [cucumber/vscode#189]
### 👓 What did you see?

v1.8.0 was never released to any Marketplace neither [open-vsx](https://open-vsx.org/extension/CucumberOpen/cucumber-official) nor [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official). It seems that the pipeline action failed [Prepare release v1.8.0 Action](https://github.com/cucumber/vscode/actions/runs/6251011331/job/17222575631)

### ✅ What did you expect to see?
Since the release has been done on 20th of September, I expected to find the release v1.8.0 in both Marketplaces

Currently the latest version available on those marketplaces is the v1.7.0

### 🔬 How could we reproduce it?

visit the links above, the latest version available is v1.7.0

**Comment by kieran-ryan** [comment]
Thanks for raising @seanlilmateus; appears to be a duplicate of #178

**Comment by seanlilmateus** [comment]
@kieran-ryan thanks for point out. this can be close then!

**Comment by seanlilmateus** [comment]
duplicate: this issue already exists #178
