### ISSUE TITLE
Extension build can not run due to invalid compatibility version for VSCode

### ISSUE THREAD

**Issue by kieran-ryan** [cucumber/vscode#190]
### 👓 What did you see?

When following the [contributing guidelines](https://github.com/cucumber/vscode/blob/main/CONTRIBUTING.md) and attempting to launch the extension locally, it fails to run. Inspecting the `Window` tab of the `Output` window, it was listed that a later version of VSCode was required - however, the latest was running (`1.85.0`).

```console
2023-12-17 20:39:40.976 [info] Started local extension host with pid 99070.
2023-12-17 20:39:41.903 [error] [/Users/<username>/cucumber/vscode]: Extension is not compatible with Code 1.85.0. Extension requires: ^2023.0.0.
```

The version listed in the extension manifest was calendar-based (`^2023.0.0`), rather than semantic versioning - which is in use and expected by VSCode (see [Visual Studio Code compatibility](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility)). This change was applied through Renovate in [99e5f3b](https://github.com/cucumber/vscode/commit/99e5f3b05d1f5bc89f8bd710a41837e5f5f2b5c8). In any case, 1.82.0 had been set to prevent using the extension with incompatible versions ([79696ca](https://github.com/cucumber/vscode/commit/79696ca3bbd3a142e9c6c3fb913b806f4e77f9d7)), and if it had changed to releases in the calendar year, it would have picked up earlier, incompatible versions in 2023 (back as far as v.1.75.0).

Ultimately, Renovate is treating `vscode` as a package dependency and attempting to update it to the latest, rather than considering it as a compatibility version for Visual Studio Code.

### ✅ What did you expect to see?

The extension runs.

### 📦 Which tool/library version are you using?

Version: 1.85.0 (Universal)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z (1 wk ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.6.0
Cucumber VSCode: 1.8.0

### 🔬 How could we reproduce it?

Follow the contributing guidelines and run the extension locally. Open the `Window` tab of the `Output` window.

### 📚 Any additional context?

The Cucumber extension was confirmed uninstalled before running the contributing guidelines.

**Comment by mpkorstanje** [comment]
> Ultimately, Renovate is treating vscode as a package dependency and attempting to update it to the latest, rather than considering it as a compatibility version for Visual Studio Code.

It looks like renovate assumes that only a single versioning scheme is in use. So a 2023.0.0 version > 1.x.y version. 

Unfortunately, I'm a little light on the details of NPM and vscode. Would you be willing to file the report instead?

**Comment by mpkorstanje** [comment]
Oddly enough, I can't seem to find where the 2023 came from in the first place.

https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/npm/extract/common/dependency.ts#L58-L60

According to Renovate it should be a Github tag. But no such tag exists.

**Comment by kieran-ryan** [comment]
> According to Renovate it should be a Github tag. But no such tag exists.

Was perplexed by the same - wonder did VSCode yank a tag.

Have reported the issue (renovatebot/renovate#26356).
