### ISSUE TITLE
Optimise bundle by storing documentation images in the GitHub CDN

### ISSUE THREAD

**Issue by kieran-ryan** [cucumber/vscode#194]
### 🤔 What's the problem you're trying to solve?

The size of the [latest release](https://github.com/cucumber/vscode/releases/tag/release%2Fv1.8.0) is 15.7MB. Extracting the extension, this is largely images used for documentation; and contains files that are not required in the bundle - such as the helper script to update settings.

This is significantly larger than the code of the extension itself, and thus represents a large overhead across downloads - particularly as the documentation images in any case are served through the GitHub CDN in the extension marketplace, rather than from the bundle.

### ✨ What's your proposed solution?

- Use GitHub CDN to store documentation images
- Extend `.vscodeignore` to include non-required files: `.github/`, `..HEAD`, `scripts/`, `RELEASING.md`, `vsc-extension-quickstart.md`

### ⛏ Have you considered any alternatives or workarounds?

User has no alternative but to download the full bundle. Not aware of a suitable alternative to proposed solution.

### 📚 Any additional context?

See [embedding images in GitHub](https://youtu.be/8088ORqS3uY?si=ffUb_8T4df8_euam) by [anthonywritescode](https://www.youtube.com/@anthonywritescode) to demonstrate how you can create static image URLs from GitHub by dragging them into an Issue or the Web Editor - which you can then reference from your code - (see screenshots below). The opinion is also provided that you shouldn't store binary files such as images in git, however the reasoning behind that opinion is not covered.

1. Drag the image to an Issue or the Web Editor within your GitHub project

    ![Screenshot 2023-12-20 at 15 37 07](https://github.com/cucumber/vscode/assets/5904340/866409fe-6611-4ccd-bd76-37f3ffd97e92)

2. GitHub will create and change this to a static URL using the GitHub CDN, which can be referenced in your code or elsewhere

    ![Screenshot 2023-12-20 at 15 37 45](https://github.com/cucumber/vscode/assets/5904340/fe7633ec-1b01-44f2-8bb2-f13ad5d33ede)

[ruff-vscode](https://github.com/astral-sh/ruff-vscode) is an example where documentation images for the extension are stored through the GitHub CDN and that excludes some of the extended paths from the bundle such as `.github/`.

**Comment by mpkorstanje** [comment]
> See [embedding images in GitHub](https://youtu.be/8088ORqS3uY?si=ffUb_8T4df8_euam) by [anthonywritescode](https://www.youtube.com/@anthonywritescode) for additional context on using the GitHub CDN over images stored in git.

I'm sorry. Videos are useful for me as explanatory documentation. They're can't be speed read.

**Comment by kieran-ryan** [comment]
> > See [embedding images in GitHub](https://youtu.be/8088ORqS3uY?si=ffUb_8T4df8_euam) by [anthonywritescode](https://www.youtube.com/@anthonywritescode) for additional context on using the GitHub CDN over images stored in git.
> 
> I'm sorry. Videos are useful for me as explanatory documentation. They're can't be speed read.

That's great feedback - I wouldn't have considered that - noted for future!
