### ISSUE TITLE
Feature syntax highlighting not working for C# project in Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by DavidMartynWood** [cucumber/vscode#200]
### 👓 What did you see?

Using the extension in vscode on Windows I can see syntax highlighting in .feature files and can drill down to the step imlementations.
Using the extension in WSL v2 I cannot see syntax highlighting in .feature files. When looking at the cucumber extension vscode reports it has not been activated.

### ✅ What did you expect to see?

Syntax highlighting should work in vcode running in WSL v2.

### 📦 Which tool/library version are you using?

* Windows 10, also tried Windows 11
* Cucumber version 1.7.0, and also tried with Cucumber version 1.8.0
* vscode 1.85.1
* C# Dev kit extension also installed
* WSL Version 2, Ubuntu 22.02.3

### 🔬 How could we reproduce it?

I have added a sample project to reproduce the issue here: https://github.com/DavidMartynWood/specflow-test

1. Install vscode
2. Install WSL & Hyper-V
3. wsl --set-default-version 2
4. Install Ubuntu in WSL from the Windows Store
5. Install dotnet 8 sdk in Windows
6. Install cucumber and C# Dev kit extensions
7. Open above project in Windows and WSL

Note that syntax highlighting works in Windows but not in WSL

Interestingly syntax highlighting works in Windows even when I don't specify any paths for `cucumber.features`

**Comment by kieran-ryan** [comment]
Thanks for the bug report @DavidMartynWood - the level of detail is excellent!

Could you advise whether what you are experiencing matches #121? Are you also not seeing step autocompletion? If so, we were missing a Minimal Reproducible Example with that ticket - which you have provided. So we may be able to close this ticket, link it and use its information to debug the issue.

Have observed tickets from other extensions relating to syntax highlighting issues with WSL (e.g. microsoft/vscode-cpptools#3942) - so there may be a common issue that we need to amend with this extension.

**Comment by DavidMartynWood** [comment]
Thank you for the quick reply. I tried again with Cucumber 1.8.0 and found that it does indeed fix the problem. I think when I tried yesterday I must have installed 1.8.0 in Windows and 1.7.0 in WSL.

The symptoms were as described in #121. No syntax highlighting, no auto complete, and no additional context menu options.
