### ISSUE TITLE
Extension can not find step files in rust project

### ISSUE THREAD

**Issue by technomage** [cucumber/vscode#202]
### 👓 What did you see?

In a workspace one of the projects is using Cucumber for rust crate.  The tests run, but the extension does not appear to be able to find the steps.  All steps are marked as undefined.  Steps are in .rs files under tests/steps, features are under test/features.  Steps included in tests as pub modules.

### ✅ What did you expect to see?

It should be able to find the steps.

### 📦 Which tool/library version are you using?

cucumber = "0.20.*"

### 🔬 How could we reproduce it?

Create a rust workspace.
Create a library crate under that.
Create features under tests/features, and steps under tests/steps
Create step functions like the screen shot and use them in a feature like the screen shot.

### 📚 Any additional context?

Steps use the #[verb(regex = r#"^...$"] syntax for rust steps with regex.
[RustFeature.pdf](https://github.com/cucumber/vscode/files/13848372/RustFeature.pdf)
[RustSteps.pdf](https://github.com/cucumber/vscode/files/13848373/RustSteps.pdf)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment]
Cheers for the bug report @technomage - was able to reproduce 👍

Fix would be required in the [rust implementation](https://github.com/cucumber/language-service/blob/1e34a962320b9632ddf3bac04e46ea2806183250/src/language/rustLanguage.ts#L9) of the [Cucumber Language Service](https://github.com/cucumber/language-service).

**Comment by kieran-ryan** [comment]
Bug resolved by @technomage. We’ll get it into an upcoming release. Thanks for your contribution
