### ISSUE TITLE
Cross-platform development scripts

### ISSUE THREAD

**Issue by binhtran432k** [cucumber/vscode#210]
### 🤔 What's the problem you've observed?

Our npm scripts use shell commands, working on Unix-like systems (Mac & Linux). To expand user reach and simplify support, let's discuss migrating them to Node.js for truly cross-platform compatibility. Share your insights & preferred approaches!

- `cp` command is not work on regular Windows systems.
  https://github.com/cucumber/vscode/blob/c3ed82d412241b996776b17b40d1603f96ad22ce/package.json#L92
- `sh` scripts is not compatible with Windows systems.
  https://github.com/cucumber/vscode/blob/c3ed82d412241b996776b17b40d1603f96ad22ce/package.json#L98-L99

### ✨ Do you have a proposal for making it better?

Since Node.js is our development environment, migrating all complex scripts to Node.js will ensure cross-platform compatibility. This leverages built-in modules like `fs` for file operations, documentation generation, and more.

### 📚 Any additional context?

This problem also occurs in [cucumber/language-server](https://github.com/cucumber/language-server) and [cucumber/language-service](https://github.com/cucumber/language-service)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by kieran-ryan** [comment]
Cheers for raising - agree on cross-compatibility; making it easy for anyone to contribute to the project is incredibly important.

The first thing I would suggest to check is what conventions are applied across Cucumber: whether there are other scripts in use and what format they take. Ensuring a consistent contributing experience across our repositories is important for maintainability. Perhaps you can take a lot at our other repositories and advise?

Secondly, I would weigh up the prospects of containerisation - which would standardise development environments and may be comparatively easier to set up and maintain.

Interested in your thoughts on the above @binhtran432k. What do you think?

**Comment by binhtran432k** [comment]
Hi @kieran-ryan,

Thanks for the thoughful response and your agreement on the importance of cross-platform compatiblity! I definitely share your sentiments about making contribution easy and accessible.

In response to your suggestion, I agree that other Node.js scripts used in Cucumber projects also lack Windows compatibility. While containerization holds promise, I propose keeping it a lower priority for now due to the following factors:
- Windows users can leverage WSL or orther virtual machines for building and deploying to their actual machines.
- Certain repositories, such as [cucumber/language-service](https://github.com/cucumber/language-service), rely on Docker within their build processes, posing significant challenges for further containerization.

I'll keep this issue open to link it with future cross-platform development efforts. Feel free to close it if it is not planned!

**Comment by kieran-ryan** [comment]
@binhtran432k, thanks for your valuable input and discussion on this issue. Given the polyglot nature of Cucumber projects, suggest we continue with scripts for present moment. However, we can absolutely continue further discussion and revisit this decision if new information comes to light.

Introducing Node scripts would add a Node installation dependency to workflow jobs beyond JavaScript. This may affect contributors working with different languages more than ourselves, who may be without a Node installation (for example, see the [makefile for the Python implementation of the gherkin parser](https://github.com/cucumber/gherkin/blob/main/python/Makefile)). As these scripts are more related to maintenance than the JavaScript implementation itself, they could be worked on by any member of the community.

Although the current script format is not perfect, it **seems** to be the accessible option for the moment, as you've also pointed out alternatives for Windows users (`Windows users can leverage WSL or other virtual machines`).

Appreciate your continued contributions and ideas - you're doing excellent work!
