### ISSUE TITLE
Simplifying Development: A Return to Monorepo Architecture

### ISSUE THREAD

**Issue by binhtran432k** [cucumber/vscode#212]
### 🤔 What's the problem you've observed?

The VSCode extension serves as a wrapper for the language server, while the language server, in turn, acts as a wrapper for the language service. This separation, though common, presents challenges for contributors in local development. Additionally, when a patch is applied to the language service, the current practice necessitates making corresponding patches to both VSCode and the language server in the development chain. Adopting a monorepo architecture could simplify this process, while also not compromising independent development and deployment.

### ✨ Do you have a proposal for making it better?

We should either create a new repository that includes all components—Cucumber VSCode, language server, and language service—or reuse the existing VSCode repository with the language server and language service integrated.

### 📚 Any additional context?

I notice that we have moved away from the monorepo approach, but for these packages, it may not be worthwhile. Some popular VSCode extensions follow this architecture, like [robotframework-lsp](https://github.com/robocorp/robotframework-lsp) and [tailwindcss-intellisense](https://github.com/tailwindlabs/tailwindcss-intellisense).

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by kieran-ryan** [comment]
Thanks for the interesting perspective @binhtran432k. Can understand some of the challenges. With a monorepo architecture, would you be able to advise:

1. How would you rectify [issues presented by the previous monorepo architecture](https://github.com/cucumber/common/issues/1724)?
2. How would you test across different source code versions of two components? For example, an in-development language-server change against an in-development language-service change of another contributor on a different branch/fork.
3. "presents challenges for contributors in local development" - would you be able to outline some of these challenges? Can you think of any other opportunities that might mitigate or resolve these challenges?

**Comment by kieran-ryan** [comment]
Will close this for now @binhtran432k, had a look at alternatives and some other repositories but unfortunately haven't located a suitable mitigation for the mentioned issues. Will keep an eye on this and reopen if encounter a suitable option; will also continue to work on improvement the development experience and documentation. Appreciate your support as always.
