### ISSUE TITLE
Recommend support for cucumber.js test runner

### ISSUE THREAD

**Issue by DavidYZL** [cucumber/vscode#222]
### Run cucumber test on VS Code Testing

I want to debug my cucumber test on VS Code, but there is no good extension to support it. I can only use the CLI every time, which is cumbersome.

And you can refer the following extensions:

[Cucumber JS Test Runner](https://github.com/mandziak-nv/vscode-cucumber-js-runner): It has bugs, I cannot run any tests.
[CucumberJS Test Runner](https://github.com/Balrog994/cucumber-test-runner): It does not support customizing cucumber's configuration file path.

**Comment by kieran-ryan** [comment]
Cheers for the feature request @DavidYZL, sounds like might match  #69? What do you think?

**Comment by DavidYZL** [comment]
I think it is same.😃 I suggest the team put it on the development agenda. I will be very grateful for everyone's efforts to make our work more convenient.

**Comment by kieran-ryan** [comment]
Awesome - closing as a duplicate. As an open source project reliant on voluntary contributions, there is no development agenda as such. Though the feature can be delivering by anyone willing to implement - PRs welcomed 🙌

Feel free to leave a thumbs up on the linked issue also - it can assist in highlighting demand for this feature to others. Sincere thanks for your interest in this project @DavidYZL!
