### ISSUE TITLE
Concatenated step definition patterns and `@And` annotation unsupported in Java

### ISSUE THREAD

**Issue by jm-paulin** [cucumber/vscode#225]
### 👓 What did you see?

The `@And` annotation is not resolved in the feature file, and the step appears as undefined. See `we create a trigger job application graph` below:

![image](https://github.com/cucumber/vscode/assets/23401647/59c2e560-53c7-4e11-a6ca-7fdc01d61520)

The associated actions are defined in `src/test/java/org/jmp/test/stepdef/TriggerJobStepDef.java`: as:

```java
  @Given("we have defined a trigger config")
  public void we_have_defined_a_trigger_config(String triggerConfigStr) {
    LOG.info("we have defined a trigger config");
  }

  @And("we create a trigger job application graph")
  public void we_create_a_trigger_job_application_graph() {
    LOG.info("we create a trigger job application graph");
  }
```

### ✅ What did you expect to see?

I would expect the step to be recognised. If I change the annotation from `@And` to `@Given` in the Step definition then it is recognised correctly.

### 📦 Which tool/library version are you using?

This is using VSCode (Windows + WSL2):
```
Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

With **Extensions installed on WSL: Ubuntu-22.04:**
```
$ code --list-extensions --show-versions    
cucumberopen.cucumber-official@1.9.0
josevseb.google-java-format-for-vs-code@1.1.1
redhat.fabric8-analytics@0.9.4
redhat.java@1.29.0
redhat.vscode-xml@0.26.1
redhat.vscode-yaml@1.14.0
timonwong.shellcheck@0.37.0
viktorzetterstrom.non-breaking-space-highlighter@0.0.3
visualstudioexptteam.intellicode-api-usage-examples@0.2.8
visualstudioexptteam.vscodeintellicode@1.3.1
vscjava.vscode-java-debug@0.57.0
vscjava.vscode-java-dependency@0.23.6
vscjava.vscode-java-pack@0.26.0
vscjava.vscode-java-test@0.41.0
vscjava.vscode-maven@0.44.0
```

Maven 3.8.6
```
$ mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven
Java version: 17.0.10, vendor: IBM Corporation, runtime: /opt/jdk-17.0.10+7
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.146.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

and Java-17:
```
$ java --version
openjdk 17.0.10 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0 (build 17.0.10+7)
Eclipse OpenJ9 VM 17.0.10.0 (build openj9-0.43.0, JRE 17 Linux amd64-64-Bit Compressed References 20240116_670 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 2aad089841f based on jdk-17.0.10+7)
```

### 🔬 How could we reproduce it?

Attaching a small maven project that replicates it for me. Simply load the project in VSCode and see what happens.

[cucumber-test.zip](https://github.com/cucumber/vscode/files/14943393/cucumber-test.zip)

**Comment by kieran-ryan** [comment]
This is perfect @jm-paulin, thanks a million for the detailed information! There were some comments on #181 where we mentioned supporting those keywords; would you be able to take a look and advise whether that matches your issue and would resolve the issue for you? If so, suggest to leave a thumbs up on that issue and advise here whether we can mark this as a duplicate and open a fix

**Comment by jm-paulin** [comment]
Hi @kieran-ryan, #181 is kind of related to this issue, but there is not enough details to know if that is the same. In my case I only have issues with `@And` and somewhat with  `@When`, If I change the annotation to `@Given` then the steps resolve correctly.

@The-BDD-Coach implied in https://github.com/cucumber/vscode/issues/130#issuecomment-2045059749 that `@And` should be supported.

**Comment by kieran-ryan** [comment]
Perfect, thanks @jm-paulin. I mentioned support for these decorators in the issue I linked; will resolve through that work.

> In my case I only have issues with @And and somewhat with @When

For `somewhat with @When` could you advise if are any cases where `@When` does not work and changing it to `@Given` does? They should be treated the same. It can be the case that some patterns may go undetected due to other issues such as issues with escapes in the Java implementation - which may happen to affect your `@when` definitions; so we would need to resolve any specific issues that may exist in those cases, based on any detail you can provide.

**Comment by kieran-ryan** [comment]
@jm-paulin, thanks for submitting this issue and providing the sample files - which proved really helpful. Beyond not supporting the `@And` and `@But` annotations, through your examples, I observed that we were not supporting concatenated strings (added together) - which was the main issue in not detecting your `@When` definitions.

I have implemented support and once we propagate releases through the Language Service and Language Server, this should resolve the issue for you.

Feel free to raise further feedback as you find it 🙌

**Comment by kieran-ryan** [comment]
@jm-paulin, now released - thanks for your contribution! If you install the latest version ([v1.10.0](https://github.com/cucumber/vscode/releases/tag/v1.10.0)), it should detect `@And` and `@But` annotations and work with concatenated strings (`"" + ""`). Looking forward to your feedback and further contributions!

**Comment by jm-paulin** [comment]
Thanks for the fix @kieran-ryan. I have verified on our main environment and it works as expected. Excellent work!

**Comment by kieran-ryan** [comment]
Awesome - thanks so much for the contribution @jm-paulin! ❤️ Looking forward to your next contributions! 💪
