### ISSUE TITLE
steps are not recognized when using "And" keyword

### ISSUE THREAD

**Issue by SkyFips** [cucumber/vscode#233]
### 👓 What did you see?

Some steps in our project are not recognized by the _"Go to definition (F12)"_ feature of VS code

### ✅ What did you expect to see?

all steps in _"features/**/*.feature"_ are recognized, if they exist

### 📦 Which tool/library version are you using?

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

cucumber: 1.10.0

### 🔬 How could we reproduce it?

1. create a new cucumber project or use existing one
1. copy the below step definition examples into _"features/step_definitions/"_
```gherkin
Feature: go to definition in VS code

  Scenario: when VS code find definitions to go to
    Given step is found by cucumber extension
    And this step is not found
    Then this step is found
    When it starts with "When" it can be found
    Given steps are always good to find, even with parameter "text"
    Given at the end of the ruby feature file seems important?!
```
1. copy the following into a feature file in _"features/"_
```ruby
# frozen_string_literal: true

Given(/^step is found by cucumber extension$/) do
  # no need to have something
end

And(/^this step is not found$/) do
  # this step is not found by cucumber go to
end

Then(/^this step is found$/) do
  # steps starting with Then are found
end

Given(/^steps are always good to find, even with parameter "(\w+)"$/) do |para|
  # steps with "Given" seems always good and also with a parameter
end

When(/^it starts with "When" it can be found$/) do
  # this step is new and starts with "And"
end

Given(/^at the end of the ruby feature file seems important?!$/) do
  # some text
end
```
1. let cucumber extension index the files
1. steps starting with _"And"_ are not recognized

### 📚 Any additional context?

https://github.com/cucumber/vscode/assets/39296120/0d8da0c4-d87d-4a4f-a028-f0b518d4dce5

**Comment by kieran-ryan** [comment]
Great catch @SkyFips - appreciate the detailed report. Fix implemented. Will be available in the next release (`1.11.0`), pending completion of additional enhancements. Keep the contributions coming 🙌

**Comment by 190031989sagar** [comment]
Actually even java script were having exactly same issue. Could you please help us with javascript too in your next release.

**Comment by zbranzov** [comment]
@kieran-ryan Javascript/typescript has the same issue. Please fix it too.

**Comment by jenisys** [comment]
Mmh, `And` and `But` steps normally require one of the `Given/When/They` keyword in your step-definition/step-implementation but not the `And`(or: `But`) decorator.

In your example above, the `And` steps follows a `Given` step.
Therefore, the `And` step in the feature file is actually a `Given` step definition, like:

```ruby
# PROBLEMATIC: Step definition from above
# WAS: And(/^this step is not found$/) do
Given(/^this step is not found$/) do
  # this step is not found by cucumber go to
end
```
