### ISSUE TITLE
Can't install extension because not compatible with current version of VS Code

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/vscode#73]
### 👓 What did you see?

While trying to install the extension on VS Code, an error message is shown: "Can't install 'cucumberopen.cucumber-official' extension because it is not compatible with the current version of Visual Studio Code (version 1.66.2)."

### 📦 Which tool/library version are you using?

Trying to install the extension from the marketplace
VSCode 1.66.2

### Addition

After restarting VSCode, it has been updated to 1.67.1. The extension installed properly on that one.
Please note that package.json specifies v1.63.2 as required vscode engine

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by aurelien-reeves** [comment]
I've downloaded the extension from the marketplace, and it appears that the package.json within the .vsix file actually specifies a vscode engine version >= 1.67

I cannot find that spec in the repo

Also, 1.67 is pretty recent. We may consider requiring at least 1.66, or even lower, to make sure user which do not have updated vscode recently can still install the extension

**Comment by aslakhellesoy** [comment]
I’ll make a new release today that doesn’t require the latest vscode.

Just fiddling a bit with the automated release process first…

**Comment by aslakhellesoy** [comment]
This is fixed in 1.0.3
