### ISSUE TITLE
Go to definition to TypeScript source is not working on Windows

### ISSUE THREAD

**Issue by remss** [cucumber/vscode#82]
### 👓 What did you see?

Go to definition to TypeScript source is not working because the file path is not correct.
It tries to open a path like `\\c:\myproject\test\features\step_definitions\app.ts\` and fails. VSCode display an error "The editor could not be opened due to an unexpected error: File is a directory"

### ✅ What did you expect to see?

The source file should be opened

### 📦 Which tool/library version are you using?

VSCode 1.68.1
VSCode Cucumber v1.2.7
A TypeScript project

**Comment by aslakhellesoy** [comment]
Thanks - this might be related to #78

**Comment by aslakhellesoy** [comment]
Fixed in https://github.com/cucumber/language-server/pull/57 and extension release 1.2.8
