### ISSUE TITLE
Weird sidebar icon with no content appearing after installing the extension

### ISSUE THREAD

**Issue by niccolomineo** [cucumber/vscode#87]
### 👓 What did you see?

A messed up sidebar icon with a messed up name and no content

### ✅ What did you expect to see?

Some kind of sidebar or no sidebar at all... I don't know if the sidebar is intended at all ('cause it doesn't show up anywhere in the README)

### 📦 Which tool/library version are you using?

Cucumber 1.2.8

### 🔬 How could we reproduce it?

1. Install Cucumber 1.2.8 on VSCode 1.69.2 for MacOs Monterey
2. Reload VScode
3. Open a project either locally or via the popular `Remote - Containers` extension
4. Look for a generic sidebar icon
5. Click on the icon
6. Acknowledge that the sidebar's metadata and content are not displayed

![Schermata 2022-07-21 alle 10 16 49](https://user-images.githubusercontent.com/5409469/180165324-5eef665e-2f92-4543-a923-577de3fc8cbc.png)

**Comment by aslakhellesoy** [comment]
The Cucumber extension doesn't have a sidebar, so I'm not sure this has anything to do with this plugin.

**Comment by niccolomineo** [comment]
If I disable the Cucumber plugin, those sidebar button and pane go away altogether.

**Comment by niccolomineo** [comment]
I tried to drag that view around and, as soon as I did so, the view's metadata and content automagically got populated (its name is "Source Control Repositories"). I have no idea why it kept showing up with those incorrect metadata at launch, but it's now fixed.
