### ISSUE TITLE
Support Multi-Root Workspaces

### ISSUE THREAD

**Issue by MeirionHughes** [cucumber/vscode#88]
### 👓 What did you see?

Not working in multi-root workspaces (only root folder works). 

### 📦 Which tool/library version are you using?

node: 14.20.0
vscode: 1.69.2
@cucumber/cucumber : 8.5.1
extension version: 1.2.8

### 🔬 How could we reproduce it?

New Folder. Add: 

add package.json
```json{
    "name": "testing",
    "private": true,
    "dependencies": {
        "@cucumber/cucumber": "^8.5.1"
    }
}
```

add foo.code-workspace

```json
{
  "folders": [
    {
      "name": "[root]",
      "path": "."
    },
    {
      "name": "lib",
      "path": "lib",
    }
  ], 
  "settings": {
    "cucumber.features": [
      "./spec/features/*.feature"
    ],
    "cucumber.glue": [
      "./spec/steps/**/*.step.ts"
    ]
  }
```
add ./lib/spec/features/test.feature
```
Feature: Demo
  Scenario: Check
    When the greeter says hello
    Then I should have heard "hello"
```
add ./lib/spec/steps/test.step.ts
```
import {When, Then} from '@cucumber/cucumber';

When('the greeter says hello', function () {
  this.msg = "hello;"
});

Then('I should have heard {string}', function (expectedResponse) {
  this.whatIHeard == expectedResponse;
});
```

Open as Workspace foo.code-workspace

Navigate to Lib Workspace Folder in the Explorer

Click on feature file to trigger index

### 📚 Any additional context?

Extension is unable to locate features or glue when in a workspace folder: 

```
Info  - 14:14:22] Reindexing...
[Info  - 14:14:22] * Found 0 feature file(s) in ["./spec/features/*.feature"]
[Info  - 14:14:22] * Found 0 steps in those feature files
[Info  - 14:14:22] * Found 0 glue file(s) in ["./spec/steps/**/*.step.ts"]
[Info  - 14:14:22] * Found 0 parameter types in those glue files
[Info  - 14:14:22] * Found 0 step definitions in those glue files
[Info  - 14:14:22] * Built 0 suggestions for auto complete
```

Copy the spec folder into the [root] workspace and open the feature file via the root, and it _will_ work: 
```
[Info  - 14:24:37] Reindexing...
[Info  - 14:24:37] * Found 1 feature file(s) in ["./spec/features/*.feature"]
[Info  - 14:24:37] * Found 2 steps in those feature files
[Info  - 14:24:37] * Found 1 glue file(s) in ["./spec/steps/**/*.step.ts"]
[Info  - 14:24:37] * Found 0 parameter types in those glue files
[Info  - 14:24:37] * Found 2 step definitions in those glue files
[Info  - 14:24:37] * Built 2 suggestions for auto complete
```
### Tried: 

I tried prefixing the glob paths with ${workspaceFolder} but it didn't work.

**Comment by MeirionHughes** [comment]
nvm... this works: 

```json
"settings": {
    "cucumber.features": [
      "**/spec/features/*.feature"
    ],
    "cucumber.glue": [
      "**/spec/steps/**/*.step.ts"
    ]
  }
 ```
and it seems smart enough to link them depending on which workspace folder they're in (i.e. if you copy the lib folder a few times. 

I suggest a quick change to the extension readme on how to deal with multi-root workspace

**Comment by kieran-ryan** [comment]
Marking issue as resolved due to configuration mentioned above using the `**` glob pattern to look in all subdirectories of the root. For documentation, an alternative option is to specify glob paths to each of the individual subdirectories we want the extension to inspect.

```json
"settings": {
    "cucumber.features": [
      "lib/spec/features/**/*.feature",
      "lib2/spec/features/**/*.feature"
    ],
    "cucumber.glue": [
      "lib/spec/steps/**/*.step.ts",
      "lib2/spec/steps/**/*.step.ts"
    ]
}
```
