### ISSUE TITLE
Feature Background topic not styled correctly. 

### ISSUE THREAD

**Issue by MeirionHughes** [cucumber/vscode#91]
### 👓 What did you see?

"Background" topics are not styled correctly - version 1.2.8

![image](https://user-images.githubusercontent.com/3584509/183451345-69333de9-ded6-4074-a7ad-a419c6edf86b.png)

### 🔬 How could we reproduce it?

Add a "Background:" section to a Feature. 

### Expected: 

Background topic text is styled same as "Feature" and Scenario"

**Comment by aslakhellesoy** [comment]
This was fixed in https://github.com/cucumber/language-service/pull/78 and will be included in the next release.
