### ISSUE TITLE
Support vscode outline panel for feature files

### ISSUE THREAD

**Issue by pkufranky** [cucumber/vscode#94]
### 🤔 What's the problem you're trying to solve?

For large feature files, it's very convient to preview the structure with vscode outline panel

### ✨ What's your proposed solution?

Support vscode outline panel

### ⛏ Have you considered any alternatives or workarounds?

I haven't found any workarounds.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by aslakhellesoy** [comment]
That's a good idea. Is this something you'd be interested in contributing @pkufranky?

**Comment by pkufranky** [comment]
> That's a good idea. Is this something you'd be interested in contributing @pkufranky?

Just a feature request. I am not ready to contribute.

**Comment by 10xtechie** [comment]
@aslakhellesoy ,
I would love to contributing on this issue. Please assign it me.

**Comment by aslakhellesoy** [comment]
My pleasure! Are you OK working on a branch in your own fork? Feel free to send a draft PR if you want feedback before you're "done" :-)

**Comment by aslakhellesoy** [comment]
Relevant Twitter Thread: https://twitter.com/CodingWthThomas/status/1572246370345717760

**Comment by 10xtechie** [comment]
@aslakhellesoy ,
Thanks for assigning it to me! Yes, I am OK working on a branch in my own fork - that is what I do always! 
Alright, I will do. Thanks for sharing the Relevant Twitter Thread!

**Comment by aslakhellesoy** [comment]
This is released in version 1.5.0

**Comment by pkufranky** [comment]
Thanks very much.
