### ISSUE TITLE
Invalid table should not be removed when formatting

### ISSUE THREAD

**Issue by pkufranky** [cucumber/vscode#96]
### 👓 What did you see?

Examples:
      | foo | bar |
      |   1 |
      
After formating, it becomes
Examples:

### ✅ What did you expect to see?

It should not remove anything when formatting.

### 📦 Which tool/library version are you using?

vscode cucumber extension, v1.2.8

### 🔬 How could we reproduce it?

In vscode, use cucumber as formatter for .feature file. 
Enter the invalid table and save, table is removed.

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by niccolomineo** [comment]
I agree with the OP and I'd like to add it is a quite serious issue at the moment.
