### ISSUE TITLE
Language support for Rust

### ISSUE THREAD

**Issue by itsezc** [cucumber/vscode#97]
### 🤔 What's the problem you're trying to solve?

Currently Rust is not supported so syntax highlighting is poor / non existent, although the usage for Cucumber in the Rust community is pretty large: https://github.com/cucumber-rs/cucumber 

### ✨ What's your proposed solution?

Adding support for Rust in the Cucumber language server

### ⛏ Have you considered any alternatives or workarounds?

- There are a number of non first party / obscure Cucumber extensions for Rust on VSCode

### 📚 Any additional context?

N/A

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by aslakhellesoy** [comment]
Moved to https://github.com/cucumber/language-service/issues/82
