### ISSUE TITLE
Publish to Open VSX Registry

### ISSUE THREAD

**Issue by jan-molak** [cucumber/vscode#98]
Hi @aslakhellesoy and the team! I'm glad you've built an official Cucumber extension for VSCode, kudos 👏🏻 

Do you think it would it be possible to publish this extension to the Open VSX Registry?

As I'm sure you know, Microsoft prohibits direct use of extensions downloaded from [Visual Studio Marketplace](https://marketplace.visualstudio.com/vscode) in non-Microsoft software, even though most extensions there are open-source and not developed or maintained by Microsoft. 

I understand that there was an issue with Open VSX not supporting renaming the Cucumber namespace to CucumberOpen, and that their suggestion is to publish to a new namespace - https://github.com/EclipseFdn/open-vsx.org/issues/1008
I also noticed that the [GitHub workflow configuration](https://github.com/cucumber/vscode/blob/35f856e7d2f6b6f6178d0e2d2107f14fd27100ae/.github/workflows/release-marketplace.yaml#L26-L29) is expected to push the extension to Open VSX, but the publishing step is [currently failing](https://github.com/cucumber/vscode/actions/workflows/release-marketplace.yaml).

Is there anything left to do to make this happen? Anything I can do to help?
I'm sure the community would greatly appreciate being able to benefit from your work.

Thanks and take care,
Jan

**Comment by aslakhellesoy** [comment]
My intention was always to publish to VSX as well. As explained in https://github.com/EclipseFdn/open-vsx.org/issues/1008#issuecomment-1127973367, VSX cannot rename the namespace.

We could of course start using a new namespace by changing this line:

https://github.com/cucumber/vscode/blob/35f856e7d2f6b6f6178d0e2d2107f14fd27100ae/package.json#L6

But that would have consequences for the extension published to the MS Marketplace. I'm not sure how to proceed.

**Comment by jan-molak** [comment]
> But that would have consequences for the extension published to the MS Marketplace. I'm not sure how to proceed.

@kineticsquid suggests that "the only way is to republish to a new namespace and then (optionally) delete the old extensions". 

The last [Release to marketplace](https://github.com/cucumber/vscode/actions/runs/2671207827) job has failed with:

```
[Release to marketplace](https://github.com/cucumber/vscode/runs/7342520149?check_suite_focus=true#step:6:46)
Error: Unknown publisher: CucumberOpen
Use the 'create-namespace' command to create a namespace corresponding to your publisher name.
```

So perhaps what is needed is to run `create-namespace` to get CucumberOpen in place and then re-publish?

[Open VSX docs](https://github.com/eclipse/openvsx/blob/master/cli/README.md#create-a-namespace) suggest that the command would like something like this:
```
ovsx create-namespace CucumberOpen
```

The docs don't state how to remove the already existing Cucumber namespace, unfortunately, but maybe that's something that @kineticsquid could help with?

**Comment by kineticsquid** [comment]
@jan-molak @aslakhellesoy Confirming you want me to remove the `Cucumber` namespace, which you'll replace with `CucumberOpen`.

**Comment by aslakhellesoy** [comment]
Hi @kineticsquid - yes, please remove `Cucumber` - I'll create a new `CucumberOpen` namespace.

**Comment by aslakhellesoy** [comment]
It's released on [Open VSX](https://open-vsx.org/extension/CucumberOpen/cucumber-official) now! Pending verification of the `cukebot` publisher.
