### ISSUE TITLE
Tables with CJK characters do not align

### ISSUE THREAD

**Issue by pkufranky** [cucumber/vscode#99]
### 👓 What did you see?

When having CJK characters in table, table is not aligned after formatting.

### ✅ What did you expect to see?

The table should be aligned, one cjk character should be calculated as two spaces instead of one.

### 📦 Which tool/library version are you using?

cucumber vscode extension, 1.2.8

### 📚 Any additional context?

expected:
![image](https://user-images.githubusercontent.com/5346/185822293-8afc63e1-2974-4016-bd95-363ca14fab2d.png)

actual:
![image](https://user-images.githubusercontent.com/5346/185822193-1d89a226-0aee-459c-9186-b38590573220.png)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by pkufranky** [comment]
btw. The "Cucumber (Gherkin) Full Support" extension just do the right thing

**Comment by kieran-ryan** [comment]
Thanks so much for contributing this issue @pkufranky! 🎉 A fix has been implemented in the gherkin formatter package and will be available in a coming release once we propagate the change to this extension. Welcome any further contributions - thanks again!
